<div id="addNewLeadContainer">
<table width="400" border="0" cellspacing="0" class="tblStyle2" style="margin: auto;">
  <thead>
  <tr>
    <th colspan="2">Sales Stats</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <th width="50%" scope="row"><div align="right"><strong>Top Sales Person </strong></div></th>
    <td width="50%"><div align="left"><?= $this->bestSalesP; ?></div></td>
  </tr>
  <tr>
    <th scope="row"><div align="right">Bottom Sales Person</div></th>
    <td><div align="left">
      <?= $this->worstSalesP; ?>
    </div></td>
  </tr>
  <tr>
    <th scope="row"><div align="right"><strong>Sales for each market</strong></div></th>
    <td><div align="left">
    <?php
		foreach ($this->schoolsSales as $school)
			echo $school['name'].' - $'.$school['value'].'<br>';
    ?></div></td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
  </tr>
  </tbody>
</table>
</div>
<?= $this->noteDiv('The stats are generated for the last 7 days.'); ?>