<div id="addNewLeadContainer">
<link href="<?= SITE_ROOT.'/css/calendar.css' ?>" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?= SITE_ROOT.'/js/calendar.js' ?>"></script>

<script type="text/javascript">

$(document).ready(function() {
	if (!$("#comparation").attr('checked')) {
		$("#previousPeriod").hide();
	}
	$('#comparation').click(function () {
		$("#previousPeriod").slideToggle();
	});
});

/*
$(document).ready(function() {
	$('#comparation').click(function () {
		if (!$("#comparation").attr('checked')) {
			$("#previousPeriod").hide();
		}
		else {
			$("#previousPeriod").show();
		}
	});
});*/

</script>

<form name="ranksReport" action="<?= $this->url(array('controller'=>'stats', 'action' => 'ranks'),'default',true); ?>" method="post">
<table width="300" border="0" cellspacing="0" class="tblStyle2" style="margin: auto;">
  <thead>
  <tr>
    <th colspan="2">Sales Rank</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td width="40%"><div align="right">Choose Period</div></td>
    <td width="60%"><div align="left">
      <input name="from_date" type="text" id="from_date" style="width:70px; text-align:center" readonly="readonly" />
      <img src="<?= SITE_ROOT."/images/icons/calendar.png" ?>" name="from_date_button" width="10" height="10" id="from_date_button" style="cursor:pointer; " />
      <script type="text/javascript">
        Calendar.setup({
            inputField     :    "from_date",
            ifFormat       :    "%m/%d/%Y",
            button         :    "from_date_button",
            singleClick    :    false,
            step           :    1
        });
   		</script>
      <br />
      to<br />
      <input name="to_date" type="text" id="to_date" style="width:70px; text-align:center" readonly="readonly" />
      <img src="<?= SITE_ROOT."/images/icons/calendar.png" ?>" name="to_date_button" width="10" height="10" id="to_date_button" style="cursor:pointer; " />
      <script type="text/javascript">
        Calendar.setup({
            inputField     :    "to_date",
            ifFormat       :    "%m/%d/%Y",
            button         :    "to_date_button",
            singleClick    :    false,
            step           :    1
        });
   		</script>
      <br />
    </div></td>
  </tr>
  <tr>
    <td colspan="2"><div align="center">
      <input name="comparation" type="checkbox" id="comparation" style="margin:0; width:auto;" value="1" />
      Increase/Decrease over previous period</div></td>
    </tr>
  <tr>
    <td colspan="2"><div align="center">
    <table width="99%" border="0" cellspacing="0" id="previousPeriod" style="display:none">
    <tbody style="border:0;">
      <tr>
        <td><div align="right">Previous Period</div></td>
        <td><div align="left">
            <input name="from_date2" type="text" id="from_date2" style="width:70px; text-align:center" readonly="readonly" />
            <img src="<?= SITE_ROOT."/images/icons/calendar.png" ?>" name="from_date_button" width="10" height="10" id="from_date_button2" style="cursor:pointer; " />
            <script type="text/javascript">
        Calendar.setup({
            inputField     :    "from_date2",
            ifFormat       :    "%m/%d/%Y",
            button         :    "from_date_button2",
            singleClick    :    false,
            step           :    1
        });
   		</script>
            <br />
          to<br />
          <input name="to_date2" type="text" id="to_date2" style="width:70px; text-align:center" readonly="readonly" />
          <img src="<?= SITE_ROOT."/images/icons/calendar.png" ?>" name="to_date_button" width="10" height="10" id="to_date_button2" style="cursor:pointer; " />
          <script type="text/javascript">
        Calendar.setup({
            inputField     :    "to_date2",
            ifFormat       :    "%m/%d/%Y",
            button         :    "to_date_button2",
            singleClick    :    false,
            step           :    1
        });
   		</script>
          <br />
        </div></td>
      </tr>
      </tbody>
    </table>
    </div>    </td>
    </tr>
  <tr>
    <td><div align="right"> Rank By</div></td>
    <td><div align="left">
<?php
// Allow sales reports only for admin
if ($this->userIsAdmin) { ?>
      <input type="radio" name="rank_by" id="radio3" value="income" style="margin:0; width:auto; margin-bottom:2px;" />
Sales $
<br />
<?php } ?>
<input type="radio" name="rank_by" id="radio4" value="enrolls" style="margin:0; width:auto;" />
No. of bookings
</div></td>
  </tr>
  <tr>
    <td><div align="right">Search By</div></td>
    <td><div align="left">
                  <input type="radio" name="search_by" id="radio" value="school" style="margin:0; width:auto;" />
                  Market
                  <input type="radio" name="search_by" id="radio2" value="sales_person" style="margin:0; width:auto; margin-left: 10px" />
                  Representative</div>    </td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2"><div align="center">
      <input type="submit" name="button" id="button" value="Submit" style="text-align:center; width:auto" />
    </div></td>
    </tr>
  </tbody>
</table>
</form>
</div>
