<table width="40%" border="0" style="margin: 0 20px 0 30px; line-height:20px;">
  <tr>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/add_small.png" width="10" height="10" /> <a href="%APP_PATH%/markets/add">Add market</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/leadsheet.png" width="10" height="10" /> <a href="%APP_PATH%/markets/edit?id=%MARKET_ID%">Market details</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/weekend.png" width="10" height="10" /> <a href="%APP_PATH%/markets/set-weekend-prices/?id=%MARKET_ID%">Set Weekend Prices</a></td>
    <td style="text-align:left">&nbsp;</td>
  </tr>
    <tr>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/browse.png" width="10" height="10" /> <a href="%APP_PATH%/markets">Browse markets</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/calendar.png" width="10" height="10" /> <a href="%APP_PATH%/markets/add-blackout-date/?id=%MARKET_ID%">Black Out Date</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/payment_add.png" width="10" height="10" /> <a href="%APP_PATH%/markets/add-special-day/?id=%MARKET_ID%">Add Special Prices</a></td>
    <td style="text-align:left">&nbsp;</td>
  </tr>
</table>