<!-- category menu -->
<?= $this->categoryMenu('/views/scripts/users/users_menu.phtml'); ?>

<!-- success message? -->
<?= ($this->succesMessage) ? $this->successDiv($this->succesMessage) : ''; ?>

<!-- error message? -->
<?= ($this->errorMessage) ? $this->errorDiv($this->errorMessage) : ''; ?>

<!-- output the leads table -->
<?= $this->table($this->tableData,$this->tableConfig); ?>

<!-- results per page links -->
<?= $this->perPageMenu($this->baseLink,$this->perPageLinksClass); ?>

<br>
<br>
<!-- pagination -->
<?= $this->pagination($this->paginationConfig) ?>

Note: When deleting users, please take in consideration the leads & bookings that belongs to that sales person<br />
as they will no longer appear in the lists.
<br /><br />
Legend: <br />
<img src="<?= SITE_ROOT ?>/images/icons/lock_opened.png" style="border:0" /> - active (click on the icon to change status)<br />
<img src="<?= SITE_ROOT ?>/images/icons/lock_closed.png" style="border:0" /> - inactive (click on the icon to change status)<br />
<img src="<?= SITE_ROOT ?>/images/icons/edit_small.png" style="border:0" /> - edit user information <br />
<img src="<?= SITE_ROOT ?>/images/icons/delete_small.png" style="border:0" /> - delete the user <br />