<table width="40%" border="0" style="margin: 0 20px 0 30px;">
  <tr>
    <td style="text-align:right"><img src="%APP_PATH%/images/icons/browse.png" width="10" height="10" /> <a href="%APP_PATH%/confirmation/list/leads">Browse leads</a></td>
    <td style="text-align:right"><img src="%APP_PATH%/images/icons/browse.png" width="10" height="10" /> <a href="%APP_PATH%/confirmation/list/booked">Browse bookings</a></td>
    <td style="text-align:right">&nbsp;</td>
  </tr>
    <tr>
    <td style="text-align:right">&nbsp;</td>
    <td style="text-align:right">&nbsp;</td>
    <td style="text-align:right">&nbsp;</td>
    <td style="text-align:right">&nbsp;</td>
  </tr>
</table>