<script type="text/javascript">
function PrintWindow(url)
    {
        var WindowObject = window.open(url, "print",
                              "width=100,height=100,top=250,left=345,toolbars=no,scrollbars=no,status=no,resizable=no,menubar=0");
        WindowObject.focus();
        //WindowObject.print();
        //setTimeout(function(){WindowObject.close();},3000);
	}
</script>
<table width="40%" border="0" style="margin: 0 20px 0 30px; line-height:20px;">
  <tr>
    <td style="text-align:left"><img src="<?= SITE_ROOT; ?>/images/icons/export_small.png" width="10" height="10" /> <a href="<?= SITE_ROOT; ?>/reports/exportsales/?type=pdf&sql=<?= $this->printSql; ?>&data=<?= $this->exportData; ?>">Export as PDF</a></td>
    <td style="text-align:left"><img src="<?= SITE_ROOT; ?>/images/icons/print.png" width="10" height="10" /> <a href="javascript:PrintWindow('<?= SITE_ROOT; ?>/reports/exportsales/?type=print&sql=<?= $this->printSql; ?>&data=<?= $this->exportData; ?>')" >Print</a></td>
  </tr>
  <tr>
     <td style="text-align:left">&nbsp;</td>
    <td style="text-align:left">&nbsp;</td>
  </tr>
</table>
<div id="addNewLeadContainer">
<table width="300" border="0" cellspacing="0" class="tblStyle2" style="margin: auto;">
  <thead>
  <tr>
    <th colspan="2">Sales Report</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <th width="50%" scope="row"><div align="right"><strong>Period </strong></div></th>
    <td width="50%"><div align="left"><?= $this->fromDate; ?> to <?= $this->toDate; ?></div></td>
  </tr>
  <tr>
    <th scope="row"><div align="right"><strong><?= $this->searchBy; ?>:</strong></div></th>
    <td><div align="left"><?= $this->searchByValue; ?></div></td>
  </tr>
  <tr>
    <th scope="row">&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row"><div align="right">Paid by Cash</div></th>
    <td>$ <?= !empty($this->sales['paid']['Cash']) ? $this->sales['paid']['Cash'] : 0; ?></td>
  </tr>
  <tr>
    <th scope="row"><div align="right">Paid by Credit Card</div></th>
    <td>$ <?= !empty($this->sales['paid']['Credit Card']) ? $this->sales['paid']['Credit Card'] : 0; ?></td>
  </tr>
  <tr>
    <th scope="row" style="border-bottom: 1px solid #fff;"><div align="right">Paid by Check</div></th>
    <td style="border-bottom: 1px solid #8997a0;">$ <?= !empty($this->sales['paid']['Check']) ? $this->sales['paid']['Check'] : 0; ?></td>
  </tr>
  <tr>
    <th scope="row"><div align="right"><strong>Total Paid *</strong></div></th>
    <td><div align="left">$ <?= array_sum($this->sales['paid']); ?></div></td>
  </tr>
  <tr>
    <th scope="row"><div align="right">Total Sales **</div></th>
    <td><div align="left"><strong>$
      <?= ($this->sales['total'] != '') ? $this->sales['total'] : '0'; ?>
    </strong></div></td>
  </tr>
  </tbody>
</table>
</div>
<?= $this->hintDiv('* Sum of all payments made by students who enrolled in that period and which are not marked for deletion or as cold leads.<br />
** Sum of total amount of each student who enrolled in that period which are not marked for deletion or as cold leads.<br />');
?>