<table width="60%" border="0" style="margin: 0 20px 0 30px; line-height:20px;">
  <tr>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/add_small.png" width="10" height="10" /> <a href="%APP_PATH%/booked/add">Add Booking</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/browse.png" width="10" height="10" /> <a href="%APP_PATH%/booked">All Bookings</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/cold_leads.png" width="10" height="10" /> <a href="%APP_PATH%/booked/?cold">Cold Leads</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/pay_full.png" width="10" height="10" /> <a href="%APP_PATH%/booked/?full">Paid in Full</a></td>
  </tr>
    <tr>
    <td style="text-align:left">&nbsp;</td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/my_leads.png" width="10" height="10" /> <a href="%APP_PATH%/booked/?my">My Bookings</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/dead_leads.png" width="10" height="10" /> <a href="%APP_PATH%/booked/?dead">Dead Leads</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/pay_due.png" width="10" height="10" /> <a href="%APP_PATH%/booked/?due">Payment Due</a></td>
  </tr>
</table>
<br />