<!-- category menu -->
<?= $this->categoryMenu('/views/scripts/leads/leads_menu.phtml'); ?>

<!-- success message? -->
<?= ($this->succesMessage) ? $this->successDiv($this->succesMessage) : ''; ?>

<!-- error message? -->
<?= ($this->errorMessage) ? $this->errorDiv($this->errorMessage) : ''; ?>

<!-- output the leads table -->
<?= $this->table($this->tableData,$this->tableConfig); ?>

<!-- results per page links -->
<?= $this->perPageMenu($this->baseLink,$this->perPageLinksClass); ?>

<br>
<br>
<!-- pagination -->
<?= $this->pagination($this->paginationConfig) ?>