<table width="70%" border="0" style="margin: 0 20px 0 30px; line-height:20px;">
  <tr>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/add_small.png" width="10" height="10" /> <a href="%APP_PATH%/leads/add/newlead">Add New Contact</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/followup_small.png" width="10" height="10" /> <a href="%APP_PATH%/leads/followups">Follow Up Reminders</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/browse.png" width="10" height="10" /> <a href="%APP_PATH%/leads">All Leads</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/cold_leads.png" width="10" height="10" /> <a href="%APP_PATH%/leads/?cold">Cold Leads</a></td>
  </tr>
    <tr>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/add_small.png" width="10" height="10" /> <a href="%APP_PATH%/leads/add/lead">Add Lead </a></td>
    <td style="text-align:left">&nbsp;</td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/my_leads.png" width="10" height="10" /> <a href="%APP_PATH%/leads/?my">My Leads</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/dead_leads.png" width="10" height="10" /> <a href="%APP_PATH%/leads/?dead">Dead Leads</a></td>
  </tr>
    <tr>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/add_small.png" width="10" height="10" /> <a href="#">Add Cold Lead</a></td>
    <td style="text-align:left">&nbsp;</td>
    <td style="text-align:left">&nbsp;</td>
    <td style="text-align:left">&nbsp;</td>
  </tr>
</table>