<?php

echo $this->categoryMenu('/views/scripts/leads/leads_menu.phtml');

if ($this->errors) {
	echo $this->errorDiv($this->errors);
}

?>

<div id="addNewLeadContainer">
<form name="addLead" action="<?= $this->url(array('controller'=>'leads','action'=>'add'),'default',true); ?>/lead" method="post">
<table width="550" border="0" cellspacing="0" class="tblStyle2" style="margin: auto;">
  <thead>
  <tr>
    <th colspan="4">Add Lead</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td width="128"><div align="right">First Name </div></td>
      <td width="132"><label>
        <div align="left">
          <input type="text" name="first_name" id="first_name" value="<?= !empty($this->formData['first_name']) ? $this->formData['first_name'] : ''?>" />
        </div>
      </label></td>
      <td width="140"><div align="right">Last Name</div></td>
      <td width="150"><div align="left">
        <input type="text" name="last_name" id="last_name" value="<?= !empty($this->formData['last_name']) ? $this->formData['last_name'] : ''?>" />
      </div></td>
    </tr>
    <tr>
 <td><div align="right">Company Name</div></td>
    <td><div align="left">
        <input type="text" name="company" id="company" value="<?= !empty($this->formData['company']) ? $this->formData['company'] : ''?>" />
    </div></td>
      <td><div align="right">Home Phone</div></td>
      <td><div align="left">
        <input type="text" name="home_phone" id="home_phone" value="<?= !empty($this->formData['home_phone']) ? $this->formData['home_phone'] : ''?>" />
      </div></td>
    </tr>
 <tr>
 <td><div align="right">Mobile Phone</div></td>
      <td><div align="left">
        <div align="left">
          <input type="text" name="mobile_phone" id="mobile_phone" value="<?= !empty($this->formData['mobile_phone']) ? $this->formData['mobile_phone'] : ''?>" />
        </div>
      </div></td>
    <td><div align="right">Fax Number</div></td>
    <td><div align="left">
        <input type="text" name="fax" id="fax" value="<?= !empty($this->formData['fax']) ? $this->formData['fax'] : ''?>" />
    </div></td>
  </tr>
    <tr>
      <td><div align="right">Address</div></td>
      <td><div align="left">
          <input type="text" name="address" id="address" value="<?= !empty($this->formData['address']) ? $this->formData['address'] : ''?>" />
      </div></td>
      <td><div align="right">City</div></td>
      <td><div align="left">
          <input type="text" name="city" id="city" value="<?= !empty($this->formData['city']) ? $this->formData['city'] : ''?>" />
      </div></td>
    </tr>
    <tr>
      <td><div align="right">State</div></td>
      <td><div align="left">
          <input type="text" name="state" id="state" value="<?= !empty($this->formData['state']) ? $this->formData['state'] : ''?>" />
      </div></td>
      <td><div align="right">Zip</div></td>
      <td><div align="left">
          <input type="text" name="zip" id="zip" style="width:40px;" value="<?= !empty($this->formData['zip']) ? $this->formData['zip'] : ''?>" />
      </div></td>
    </tr>
    <tr>
      <td><div align="right">Email Address</div></td>
      <td><div align="left">
          <input type="text" name="email" id="email" value="<?= !empty($this->formData['email']) ? $this->formData['email'] : ''?>" />
      </div></td>
      <td><div align="right">Market</div></td>
      <td><label for="campus_id"></label>
          <div align="left">
            <?= $this->formSelect('campus_id','select',array('style' => 'font-size:11px'),$this->campuses); ?>
        </div></td>
    </tr>
    
    <tr>
      <td><div align="right">Contact via SMS</div></td>
      <td><div align="left">
          <label>
          <input type="radio" name="via_sms" value="Yes" style="width:auto;" />
            Yes</label>
          <label>
          <input name="via_sms" type="radio" style="width:auto;" value="No" checked="checked" />
            No</label>
      </div></td>
      <td><div align="right">&nbsp;</div></td>
      <td><div align="left">&nbsp;</div></td>
    </tr>
  
    <tr>
      <td><div align="right">Best time to contact</div></td>
      <td><div align="left">
          <input type="text" name="best_contact_time" id="best_contact_time" value="<?= !empty($this->formData['best_contact_time']) ? $this->formData['best_contact_time'] : ''?>" />
      </div></td>
      <td><div align="right">Hear about us</div></td>
      <td><label for="label"></label>
          <div align="left">
            <input type="text" name="hear_about" id="label" value="<?= !empty($this->formData['hear_about']) ? $this->formData['hear_about'] : ''?>" />
        </div></td>
    </tr>
  <tr>
    <td><div align="right"> Contact Method</div></td>
    <td><div align="left">
    <label><input type="radio" name="contact_method" value="Phone" style="width:auto;" />Phone</label>
    <label><input name="contact_method" type="radio" style="width:auto;" value="Email" checked="checked" /> Email</label>
    </div></td>
    <td><div align="right">Comments</div></td>
    <td rowspan="2">
    <div align="left">
      <textarea name="comments" id="comments" style="width:100px; height: 40px; margin:0;"><?= !empty($this->formData['comments']) ? $this->formData['comments'] : ''?></textarea>
    </div></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    </tr>
  <tr>
    <td colspan="4"><div align="center">
      <input type="submit" name="button" id="button" value="Save Lead >>" style="text-align:center; width:auto" />
    </div></td>
    </tr>
  </tbody>
</table>
</form>
</div>
