<table width="50%" border="0" style="margin: 0 20px 0 30px; line-height:20px;">
  <tr>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/profile_small.png" width="10" height="10" /> <a href="%APP_PATH%/profile/?type=%LEAD_TYPE%&id=%LEAD_ID%">Profile</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/edit_small.png" width="10" height="10" /> <a href="%APP_PATH%/profile/edit/?type=%LEAD_TYPE%&id=%LEAD_ID%">Edit</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/leadsheet.png" width="10" height="10" /> <a href="%APP_PATH%/profile/quote/?type=%LEAD_TYPE%&id=%LEAD_ID%">New Quote</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/cold_leads.png" width="10" height="10" /> <a href="%APP_PATH%/profile/changetype/?tocold&type=%LEAD_TYPE%&id=%LEAD_ID%">Mark as Cold Lead</a></td>
  </tr>
    <tr>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/email_small.png" width="10" height="10" /> <a href="%APP_PATH%/profile/contact/?type=%LEAD_TYPE%&id=%LEAD_ID%">Contact</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/delete_small.png" width="10" height="10" /> <a href="#" onclick="showDeleteReason('%APP_PATH%/%LEAD_TYPE%/delete','%LEAD_ID%')">Delete</a></td>
    <td style="text-align:left">&nbsp;<!-- <img src="%APP_PATH%/images/icons/payment_add.png" width="10" height="10" /> <a href="%APP_PATH%/profile/payment/?type=%LEAD_TYPE%&id=%LEAD_ID">Add Payment</a> --></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/dead_leads.png" width="10" height="10" /> <a href="%APP_PATH%/profile/changetype/?todead&type=%LEAD_TYPE%&id=%LEAD_ID%">Mark as Dead Lead</a></td>
  </tr>
</table>