<?php
echo $this->categoryMenu('/views/scripts/profile/profile_menu.phtml');

if ($this->errors) {
	echo $this->errorDiv($this->errors);
}

?>

<div id="addNewLeadContainer">
<link href="<?= SITE_ROOT.'/css/calendar.css' ?>" media="screen" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<?= SITE_ROOT.'/css/jquery.cluetip.css';?>" type="text/css" />
<script type="text/javascript" src="<?= SITE_ROOT.'/js/calendar.js' ?>"></script>
<script src="<?= SITE_ROOT.'/js/jquery.hoverIntent.js'; ?>" type="text/javascript"></script>
<script language="javascript" src="<?= SITE_ROOT.'/js/jquery.cluetip.js'; ?>"></script>

<script language="javascript">
$('#sticky').cluetip({sticky: true, closePosition: 'title'});
</script>
<script type="text/javascript">
var quoteId = <?= $this->lId;?>;
$(document).ready(function() {
  $('#addPayment').cluetip({
  		'sticky': true,
		'closePosition': 'title',
		closeText: 'Close',
		title: 'title',
		activation: 'click',
		positionBy: 'bottomTop',
		dropShadow: false,
    	fx: {open:'fadeIn', openSpeed:  '500'},
		width: '350',
		ajaxCache: false,
		ajaxProcess:      function(data) {
    						amountPaid = parseFloat($("#paid_amount").val());
    						amountTotal = parseFloat($("#total_amount").val());
    						leftToPay = amountTotal - amountPaid;
    						if (leftToPay == amountPaid) {
        						leftToPay = 0;
    						}
						    data = data.replace(/%LEAD_TYPE%/,'<?php echo $this->leadType; ?>');
						    data = data.replace(/%LEAD_ID%/,'<?php echo $this->leadId; ?>');
						    data = data.replace(/%QUOTE_ID%/, quoteId);
						    data = data.replace(/%LEFT_TO_PAY%/, leftToPay);
						    data = data.replace(/%TOTAL_AMOUNT%/, amountTotal);
						    data = data.replace(/%DISCOUNT%/, <?php echo $this->marketFullPayDiscount; ?>);
							data = data.replace(/%FORM_URL%/,'<?php echo $this->url(array("controller"=>"profile","action"=>"payment"),"default",true); ?>');
							//alert(data);
							return data;
		}
  });
  $('#addEquipment').cluetip({
		'sticky': true,
		'closePosition': 'title',
		closeText: 'Close',
		title: 'title',
		activation: 'click',
		positionBy: 'bottomTop',
		dropShadow: false,
		fx: {open:'fadeIn', openSpeed:  '500'},
		width: '350',
		ajaxCache: false,
		ajaxProcess:      function(data) {
							return data;
		}
	});

  $("#addQuote").submit(function(mye) {
	  // check time format
	  timeFrom = $("#time_from_hour").val();
	  timeTo = $("#time_to_hour").val();

	  if (!timeFrom.match(/^[0-9]{1,2}:[0-9]{2}$/)) {
		  alert('Invalid "from" hour format');
		  mye.preventDefault();
	  }
	  if (!timeTo.match(/^[0-9]{1,2}:[0-9]{2}$/)) {
		  alert('Invalid "to" hour format');
		  mye.preventDefault();
	  }
  });

  refreshEquipments(false);
  refreshTotalAmount(false);

  $('#manual_total').change(refreshTotalAmount(true));
});

function bindRemLinks() {
	$(".rem-equipment").click(function(mye) {
		mye.preventDefault();
		$.ajax({
			cache: false,
			type: 'POST',
			url: $(this).attr("href"),
			success: function(data, textStatus, reqObj) {

			},
			error: function(XMLHttpRequest, textStatus, errorThrown) {
				alert('The equipment was not removed - ' + textStatus);
			}
		});
		$(this).parent().parent().fadeOut(500, function() { refreshEquipments(true); });
		
	});
};

function updateEventDate(cal) {
	var date = cal.date;
	eventDate = date.print("%m/%d/%Y");
	$.get("<?= $this->url(array('controller'=>'profile','action'=>'update-event-date'),'default',true); ?>?qid=" + quoteId + "&event_date=" + eventDate);
}
function refreshTotalAmount(force) {
	$.get("<?= $this->url(array('controller'=>'profile','action'=>'update-total-price'),'default',true); ?>?qid=" + quoteId + "&force=" + force, function(data) { if ('error' == data.substr(0,5)) alert('An error has occured: ' + data.substr(6)); else $("#total_amount").val(data) });
}
function refreshEquipments(force) {
	showLoading();
	$("#equipmentTable").load("<?= $this->url(array('controller'=>'profile','action'=>'quote-get-equipment'),'default',true); ?>?id=" + quoteId, function(responseText, textStatus, XMLHttpRequest) { bindRemLinks(); refreshTotalAmount(force); });
}
function showLoading() {
	$("#equipmentTable").html('<tr><td colspan="4" style="text-align:center"><img src="<?php echo SITE_ROOT; ?>/images/loading.gif" /></td></tr>');
}
</script>

<form name="addQuote" id="addQuote" action="<?= $this->url(array('controller'=>'profile','action'=>'quote'),'default',true).'/?type='.$this->leadType.'&id='.$this->leadId; ?>" method="post">
<table width="550" border="0" cellspacing="0" class="tblStyle2" style="margin: auto;">
<caption>Quote</caption>
  <thead>
  <tr>
    <th colspan="3"><div align="left">Basic Info</div></th>
    <th><div align="right" style="font-size:11px; font-weight:normal;"><a href="<?= $this->url(array('controller'=>'profile','action'=>'quote'),'default',true).'/?useProfile&type='.$this->leadType.'&id='.$this->leadId.'&lId='.$this->lId; ?>">use profile info</a></div></th>
  </tr>
  </thead>
  <tbody>
    <tr>
      <td width="128"><div align="right">First Name </div></td>
      <td width="132">
          <div align="left">
            <input type="text" name="first_name" id="first_name" value="<?= !empty($this->formData['first_name']) ? $this->formData['first_name'] : ''?>" />
          </div></td>
      <td width="140"><div align="right">Last Name</div></td>
      <td width="150"><div align="left">
          <input type="text" name="last_name" id="last_name" value="<?= !empty($this->formData['last_name']) ? $this->formData['last_name'] : ''?>" />
      </div></td>
    </tr>
    <tr>
      <td><div align="right">Company Name</div></td>
      <td><div align="left">
          <input type="text" name="company" id="company" value="<?= !empty($this->formData['company']) ? $this->formData['company'] : ''?>" />
      </div></td>
      <td><div align="right">Home Phone</div></td>
      <td><div align="left">
          <input type="text" name="home_phone" id="home_phone" value="<?= !empty($this->formData['home_phone']) ? $this->formData['home_phone'] : ''?>" />
      </div></td>
    </tr>
    <tr>
     <td><div align="right">Mobile/Other Phone</div></td>
      <td><div align="left">
          <input type="text" name="mobile_phone" id="mobile_phone" value="<?= !empty($this->formData['mobile_phone']) ? $this->formData['mobile_phone'] : ''?>" />
      </div></td>
    <td><div align="right">Fax Number</div></td>
    <td><div align="left">
        <input name="fax" type="text" id="fax" value="<?= !empty($this->formData['fax']) ? $this->formData['fax'] : '' ?>" />
    </div></td>
  </tr>
    <tr>
      <td><div align="right">Address</div></td>
      <td><div align="left">
          <input type="text" name="address" id="address" value="<?= !empty($this->formData['address']) ? $this->formData['address'] : ''?>" />
      </div></td>
      <td><div align="right">City</div></td>
      <td><div align="left">
          <input type="text" name="city" id="city" value="<?= !empty($this->formData['city']) ? $this->formData['city'] : ''?>" />
      </div></td>
    </tr>
    <tr>
      <td><div align="right">State</div></td>
      <td><div align="left">
          <input type="text" name="state" id="state" value="<?= !empty($this->formData['state']) ? $this->formData['state'] : ''?>" />
      </div></td>
      <td><div align="right">Zip</div></td>
      <td><div align="left">
          <input type="text" name="zip" id="zip" style="width:40px;" value="<?= !empty($this->formData['zip']) ? $this->formData['zip'] : ''?>" />
      </div></td>
    </tr>
    <tr>
      <td><div align="right">Email Address</div></td>
      <td><div align="left">
          <input type="text" name="email" id="email" value="<?= !empty($this->formData['email']) ? $this->formData['email'] : ''?>" />
      </div></td>
      <td><div align="right">Market</div></td>
      <td><label for="campus_id"></label>
          <div align="left">
            <?= $this->formSelect('campus_id',(!empty($this->selectedCampus) ? $this->selectedCampus : 'select'),array('style' => 'font-size:11px'),$this->campuses); //$this->campuses[$this->selectedCampus]; ?>
        </div></td>
    </tr>
    <tr>
	  <td><div align="right">Hear about us</div></td>
      <td><div align="left">
        <input type="text" name="hear_about" id="hear_about" value="<?= !empty($this->formData['hear_about']) ? $this->formData['hear_about'] : ''?>" />
      </div></td>
      <td><div align="right">Market Representative</div></td>
      <td><div align="left">
          <?= $this->selectedSPerson != 0 ? $this->sPersons[$this->selectedSPerson] : 'None' /*$this->formSelect('sales_person_id',$this->selectedSPerson,array('style' => 'font-size:11px'),$this->sPersons);*/ ?>
      </div></td>
    </tr>
    <tr>
      <th colspan="4" scope="row"><div align="left">Party/Event Details
      </div>	  </th>
    </tr>
    <tr>
    	<td><div align="right">Event Location</div></td>
    	<td colspan="3"><div align="left">
        <input type="text" name="event_location" id="event_location" style="width:200px;" value="<?= !empty($this->formData['event_location']) ? $this->formData['event_location'] : ''?>" />
        </div></td>
    </tr>
    <tr>
      <td><div align="right">Event Date</div></td>
      <td><div align="left">
        <input type="text" name="event_date" id="event_date" style="width:70px; text-align:center" value="<?= !empty($this->formData['event_date']) ? $this->formData['event_date'] : ''?>" />
        <img src="<?= SITE_ROOT."/images/icons/calendar.png" ?>" name="event_date_button" width="10" height="10" id="event_date_button" style="cursor:pointer; " />
        <script type="text/javascript">
        Calendar.setup({
            inputField     :    "event_date",
            ifFormat       :    "%m/%d/%Y",
            button         :    "event_date_button",
            singleClick    :    false,
            step           :    1,
            onUpdate	   :    updateEventDate
        });
   		</script>
        </div></td>
      <td><div align="right">No. of Guests</div></td>
      <td><div align="left">
        <input type="text" name="no_of_guests" id="no_of_guests" style="width:40px;" value="<?= !empty($this->formData['no_of_guests']) ? $this->formData['no_of_guests'] : ''?>" />
        </div></td>
    </tr>
    <tr style="display: none">
      <td><div align="right">Time</div></td>
      <td colspan="3"><div align="left">
            <input name="time_from_hour" type="text" id="time_from_hour" style="text-align:center; width:40px;" value="<?= !empty($this->formData['time_from_hour']) ? $this->formData['time_from_hour'] : '00:00'?>" size="5">
            <select name="time_from_time" id="time_from_time" style="font-size:11px">
                 <option value="AM"<?php if (!empty($this->formData['time_from_time']) && $this->formData['time_from_time'] == 'AM') echo ' selected="selected"'; ?>>AM</option>
            	<option value="PM"<?php if (!empty($this->formData['time_from_time']) && $this->formData['time_from_time'] == 'PM') echo ' selected="selected"'; ?>>PM</option>
			</select>
          &nbsp;&nbsp;to&nbsp;&nbsp;
          <input name="time_to_hour" type="text" id="time_to_hour" style="text-align:center; width:40px;" value="<?= !empty($this->formData['time_to_hour']) ? $this->formData['time_to_hour'] : '00:00'?>" size="5">
            <select name="time_to_time" id="time_to_time" style="font-size:11px;">
                <option value="AM"<?php if (!empty($this->formData['time_to_time']) && $this->formData['time_to_time'] == 'AM') echo ' selected="selected"'; ?>>AM</option>
            	<option value="PM"<?php if (!empty($this->formData['time_to_time']) && $this->formData['time_to_time'] == 'PM') echo ' selected="selected"'; ?>>PM</option>
			</select>
      </div></td>
    </tr>
    <tr>
      <td><div align="right">Event Length</div></td>
      <td>
        <div align="left">
        <input type="text" name="no_of_hours" id="no_of_hours" style="width:40px;" value="<?= !empty($this->formData['no_of_hours']) ? $this->formData['no_of_hours'] : '3'?>" /> hours
        </div>
      </td>
    </tr>
    <tr>
      <td><div align="right">Party/Event Type</div></td>
      <td colspan="3"><div align="left">
       
      <input name="event_type" type="radio" value="Fundraiser" id="event_type_fundraiser" style="width:auto;">
      <label for="event_type_fundraiser">Fundraiser</label>

      <input name="event_type" type="radio" value="Convention" id="event_type_convention" style="width:auto; margin-left:10px;">
      <label for="event_type_convention">Convention</label>
	  
      <input name="event_type" type="radio" value="Party" id="event_type_party" style="width:auto; margin-left:10px;">
      <label for="event_type_party">Party</label>
	  
      <input name="event_type" type="radio" value="Other" id="event_type_other" style="width:auto; margin-left:10px;">
      <label for="event_type_other">Other</label>
      </div></td>
    </tr>
     <tr>
      <td><div align="right">Delivery Time</div></td>
      <td><div align="left">
		<input name="time_delivery_hour" type="text" id="time_delivery_hour" style="text-align:center; width:40px;" value="<?= !empty($this->formData['time_delivery_hour']) ? $this->formData['time_delivery_hour'] : '00:00'?>" size="5">
            <select name="time_delivery_time" id="time_delivery_time" style="font-size:11px;">
                 <option value="AM"<?php if (!empty($this->formData['time_delivery_time']) && $this->formData['time_delivery_time'] == 'AM') echo ' selected="selected"'; ?>>AM</option>
            	<option value="PM"<?php if (!empty($this->formData['time_delivery_time']) && $this->formData['time_delivery_time'] == 'PM') echo ' selected="selected"'; ?>>PM</option>
			</select>
      </div></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <!-- equipment details -->
    <tr>
      <th colspan="4" scope="row"><div align="left">Tables / Services Info</div></th>
    </tr>
    <tr>
    	<td colspan="3" id="equipmentTable">&nbsp;</td>
    	<td valign="middle"><div align="center" style="margin: 20px;">
    		<?php $addEquipmentUrl = $this->url(array('controller' => 'profile', 'action' => 'quote-add-equipment')) . "?quoteId={$this->lId}"; ?>
    		<a href="<?= $addEquipmentUrl; ?>" id="addEquipment" rel="<?= $addEquipmentUrl; ?>" title="Add equipment">Add Equipment</a>
    	</div></td>
    </tr>
    <!-- end equipment details -->
    <tr>
      <th colspan="4" scope="row"><div align="left">Payment Info
      </div>	  </th>
      </tr>
    <tr>
      <td><div align="right">Paid Amount</div></td>
      <td><div align="left">
        <input type="text" name="paid_amount" id="paid_amount" style="width:40px;text-align:center" value="<?= !empty($this->formData['paid_amount']) ? $this->formData['paid_amount'] : '0'; ?>" />
      </div></td>
      <td colspan="2"><div align="center"><a href="<?= SITE_ROOT.'/bin/_add.php'; ?>" id="addPayment" rel="<?= SITE_ROOT.'/bin/_add.php'; ?>" title="Add payment">Add payment</a></div></td>
      </tr>
    <tr>
      <td><div align="right"><strong>Total Amount</strong></div></td>
      <td><div align="left">
        <input type="text" name="total_amount" id="total_amount" style="width:40px;text-align:center" value="<?= !empty($this->formData['total_amount']) ? $this->formData['total_amount'] : '0'?>" readonly="readonly" />
      </div></td>
      <td><div align="right"><strong>Override Total</strong></div></td>
      <td><div align="left">
        <input type="text" name="manual_total" id="manual_total" style="width:40px;text-align:center" value="<?= !empty($this->formData['manual_total']) ? $this->formData['manual_total'] : '0'?>" />
      </div></td>
    </tr>
    <tr>
      <th colspan="4" scope="row"><div align="left">Custom Email Message</div></th>
    </tr>
    <tr>
      <td colspan="4">
      <p>
      Include the following message when using the send option:
      </p>
<?php
    $newMsg = <<<MSGEND
Dear {$this->formData['first_name']} {$this->formData['last_name']},

We have attached the requested quote. Please contact us if you have any questions.

--
{$this->sPersons[$this->selectedSPerson]}
MSGEND;
?>
<textarea name="email_body" id="email_body" cols="80" rows="10">
<?= !empty($this->formData['email_body']) ? $this->formData['email_body'] : $newMsg ?>
</textarea>
      </td>
    </tr>
    <tr>
      <th colspan="4" scope="row"><div align="left">Misc. </div></th>
    </tr>
    <tr>
      <td><div align="right">Notes</div></td>
      <td><div align="left">
        <textarea name="comments" id="comments" style="width:100px; height: 50px; margin:0;"><?= !empty($this->formData['comments']) ? $this->formData['comments'] : ''?></textarea>
      </div></td>
      <td colspan="2">
		<div align="left" style="width:45%; float:left; margin-left:20px; margin-top:10px;">
        <input name="output_mode" type="radio" id="radio" value="X" checked="checked" style="width:auto" />
        Save<br />
        <input type="radio" name="output_mode" id="radio2" value="XS" style="width:auto" />
        Save &amp; Send<br />
     	 <input name="output_mode" type="radio" id="radio" value="D" style="width:auto" />
        Export<br />
      </div>
      <div align="left" style="width:45%; float:left; margin-top:10px;">
          <input type="radio" name="output_mode" id="radio3" value="DS" style="width:auto" />
        Export &amp; Send<br />
        <input type="radio" name="output_mode" id="radio4" value="S" style="width:auto" />
        Send Only<br />
        <input type="radio" name="output_mode" id="radio2" value="I" style="width:auto" />
        Print<br />
      </div>
      </td>
      </tr>
    <tr>
    <td colspan="4"><div align="center">
      <!-- <input type="hidden" name="campus_id" value="<?= $this->selectedCampus;?>" /> -->
      <input type="hidden" name="sales_person_id" value="<?= $this->selectedSPerson;?>" />
      <input type="hidden" name="class_info" value="<?= $this->classTime;?>" />
      <input type="hidden" name="lId" value="<?= $this->lId;?>" />
      <input type="submit" name="button" id="proceed" value="Proceed &gt;&gt;" style="text-align:center; width:auto" />
      </div></td>
    </tr>
  </tbody>
</table>
</form>
</div>
