  <table width="90%" border="0" cellspacing="0" class="tblStyle2" style="margin: auto;">
  <caption>Basic Details</caption>
  	<thead>
    <tr>
      <th colspan="4" scope="col">Basic Details</th>
      </tr>
    </thead>
    <tbody>
    <tr>
      <td width="25%" style="text-align:right;font-weight:bold;">First Name</td>
      <td width="25%" style="text-align:left;">{first_name}</td>
      <td width="25%" style="text-align:right;font-weight:bold;">Contact Method</td>
      <td width="25%" style="text-align:left;">{contact_method}</td>
    </tr>
    <tr>
      <td style="text-align:right;font-weight:bold;">Last Name</td>
      <td style="text-align:left;">{last_name}</td>
      <td style="text-align:right;font-weight:bold;">Company Name</td>
      <td style="text-align:left;">{company}</td>
    </tr>
    <tr>
      <td style="text-align:right;font-weight:bold;">Address</td>
      <td style="text-align:left;" colspan="3">{address}</td>
    </tr>
    <tr>
	  <td style="text-align:right;font-weight:bold;">City, State, Zip</td>
      <td style="text-align:left;" colspan="3">{city} {state} {zip}</td>
    </tr>
    <tr>
      <td style="text-align:right;font-weight:bold;">Email Address</td>
      <td style="text-align:left;">{email}</td>
      <td style="text-align:right;font-weight:bold;">Home Phone</td>
      <td style="text-align:left;">{home_phone}</td>
    </tr>
    <tr>
      <td style="text-align:right;font-weight:bold;">Mobile Phone</td>
      <td style="text-align:left;">{mobile_phone}</td>
      <td style="text-align:right;font-weight:bold;">Fax</td>
      <td style="text-align:left;">{fax}</td>
    </tr>
    <tr>
      <td style="text-align:right;font-weight:bold;">Contact Via SMS</td>
      <td style="text-align:left;">{via_sms}</td>
      <td style="text-align:right;font-weight:bold;">Market</td>
      <td style="text-align:left;">{campus}</td>
    </tr>
    <tr>
      <td style="text-align:right;font-weight:bold;">Contact Name</td>
      <td style="text-align:left;">{ev_day_cname}</td>
      <td style="text-align:right;font-weight:bold;">Contact Number</td>
      <td style="text-align:left;">{ev_day_cno}</td>
    </tr>
    <tr>
      <td style="text-align:right;font-weight:bold;">Best Contact Time</td>
      <td style="text-align:left;">{best_contact_time}</td>
      <td style="text-align:right;font-weight:bold;">Hear about us</td>
      <td style="text-align:left;">{hear_about}</td>
    </tr>
    <tr>
      <td style="text-align:right;font-weight:bold;">Comments</td>
      <td colspan="2" style="text-align:left;">{comments}</td>
      <td>&nbsp;</td>
    </tr>
    </tbody>
  </table>