<table width="40%" border="0" style="margin: 0 20px 0 30px; line-height:20px;">
  <tr>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/add_small.png" width="10" height="10" /> <a href="%APP_PATH%/inventory/add">Add inventory item</a></td>
    <td style="text-align:left"><img src="%APP_PATH%/images/icons/browse.png" width="10" height="10" /> <a href="%APP_PATH%/inventory">Browse invetory items</a></td>
    <td style="text-align:left">&nbsp;</td>
    <td style="text-align:left">&nbsp;</td>
  </tr>
    <tr>
    <td style="text-align:left"></td>
    <td style="text-align:left">&nbsp;</td>
    <td style="text-align:left">&nbsp;</td>
    <td style="text-align:left">&nbsp;</td>
  </tr>
</table>